<template>
	<span>
		<div class="ui attached segment">
			<div class="ui middle aligned divided list">
				<div class="item" v-for="command in commands">
					<div class="right floated content">
						<div class="ui horizontal label" v-bind:class="{ blue: command.theme == 'blue', red: command.theme == 'red', green: command.theme == 'green' }">{{ new Date(command.timestamp).toLocaleString() }}</div>
					</div>
					<p>{{ command.content }}</p>
				</div>
			</div>
		</div>
		<div class="ui bottom attached segment">
			<div class="ui search">
				<div class="ui action fluid input">
					<input type="text" class="prompt" @keyup.enter="sendCommand" v-model="command">
					<button class="ui blue right labeled icon button" @click="sendCommand">
						<i class="send icon"></i>
						Send command
					</button>
					<button class="ui orange right labeled icon button">
						<i class="bomb icon"></i>
						Clear console
					</button>
				</div>
				<div class="results"></div>
			</div>
		</div>
	</span>
</template>

<script>
export default {

	data() {
		return {
			commands: [],
			command: ''
		}
	},

	methods: {
		sendCommand(e) {
			if (!this.command) return;
			this.commands.push({content: this.command, timestamp: Date.now(), theme: 'blue'});
			axios.post('/admin/rcon', {
				cmd: this.command
			}).then(res => {
				if (res.data.status == 'error') {
					this.commands.push({content: res.data.error, timestamp: Date.now(), theme: 'red'});
				} else {
					this.commands.push({content: res.data.response, timestamp: Date.now(), theme: 'green'});
				}
			});
			this.command = '';
		}
	},

	mounted() {
		$('.ui.search').search({
			source: [
				{title: "achievement give *", },
				{title: "achievement give * &lt;player&gt;"},
				{title: "achievement give &lt;name&gt;"},
				{title: "achievement give &lt;name&gt; &lt;player&gt;"},
				{title: "achievement take *"},
				{title: "achievement take * &lt;player&gt;"},
				{title: "achievement take &lt;name&gt;"},
				{title: "achievement take &lt;name&gt; &lt;player&gt;"},
				{title: "ban &lt;name&gt;"},
				{title: "ban &lt;name&gt; &lt;reason&gt;"},
				{title: "ban-ip &lt;address&gt;"},
				{title: "ban-ip &lt;name&gt;"},
				{title: "ban-ip &lt;address&gt; &lt;reason&gt;"},
				{title: "ban-ip &lt;name&gt; &lt;reason&gt;"},
				{title: "banlist ips"},
				{title: "banlist players"},
				{title: "blockdata &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;dataTag&gt;"},
				{title: "clear"},
				{title: "clear &lt;player&gt;"},
				{title: "clear &lt;player&gt; &lt;item&gt;"},
				{title: "clear &lt;player&gt; &lt;item&gt; &lt;data&gt;"},
				{title: "clear &lt;player&gt; &lt;item&gt; &lt;data&gt; &lt;maxCount&gt;"},
				{title: "clear &lt;player&gt; &lt;item&gt; &lt;data&gt; &lt;maxCount&gt; &lt;dataTag&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; filtered force &lt;tileName&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; filtered force &lt;tileName&gt; &lt;dataValue&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; filtered force &lt;tileName&gt; &lt;state&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; filtered move &lt;tileName&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; filtered move &lt;tileName&gt; &lt;dataValue&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; filtered move &lt;tileName&gt; &lt;state&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; filtered normal &lt;tileName&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; filtered normal &lt;tileName&gt; &lt;dataValue&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; filtered normal &lt;tileName&gt; &lt;state&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked force &lt;tileName&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked force &lt;tileName&gt; &lt;dataValue&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked force &lt;tileName&gt; &lt;state&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked move &lt;tileName&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked move &lt;tileName&gt; &lt;dataValue&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked move &lt;tileName&gt; &lt;state&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked normal &lt;tileName&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked normal &lt;tileName&gt; &lt;dataValue&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked normal &lt;tileName&gt; &lt;state&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; replace"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; replace force &lt;tileName&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; replace force &lt;tileName&gt; &lt;dataValue&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; replace force &lt;tileName&gt; &lt;state&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; replace move &lt;tileName&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; replace move &lt;tileName&gt; &lt;dataValue&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; replace move &lt;tileName&gt; &lt;state&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; replace normal &lt;tileName&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; replace normal &lt;tileName&gt; &lt;dataValue&gt;"},
				{title: "clone &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; replace normal &lt;tileName&gt; &lt;state&gt;"},
				{title: "debug start"},
				{title: "debug stop"},
				{title: "defaultgamemode survival"},
				{title: "defaultgamemode creative"},
				{title: "defaultgamemode adventure"},
				{title: "defaultgamemode spectator"},
				{title: "deop &lt;player&gt;"},
				{title: "difficulty peaceful"},
				{title: "difficulty easy"},
				{title: "difficulty normal"},
				{title: "difficulty hard"},
				{title: "effect &lt;player&gt; clear"},
				{title: "effect &lt;player&gt; minecraft:speed"},
				{title: "effect &lt;player&gt; minecraft:speed &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:speed &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:speed &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:speed &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:slowness"},
				{title: "effect &lt;player&gt; minecraft:slowness &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:slowness &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:slowness &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:slowness &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:haste"},
				{title: "effect &lt;player&gt; minecraft:haste &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:haste &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:haste &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:haste &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:mining_fatigue"},
				{title: "effect &lt;player&gt; minecraft:mining_fatigue &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:mining_fatigue &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:mining_fatigue &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:mining_fatigue &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:strength"},
				{title: "effect &lt;player&gt; minecraft:strength &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:strength &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:strength &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:strength &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:instant_health"},
				{title: "effect &lt;player&gt; minecraft:instant_health &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:instant_health &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:instant_health &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:instant_health &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:instant_damage"},
				{title: "effect &lt;player&gt; minecraft:instant_damage &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:instant_damage &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:instant_damage &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:instant_damage &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:jump_boost"},
				{title: "effect &lt;player&gt; minecraft:jump_boost &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:jump_boost &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:jump_boost &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:jump_boost &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:nausea"},
				{title: "effect &lt;player&gt; minecraft:nausea &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:nausea &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:nausea &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:nausea &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:regeneration"},
				{title: "effect &lt;player&gt; minecraft:regeneration &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:regeneration &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:regeneration &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:regeneration &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:resistance"},
				{title: "effect &lt;player&gt; minecraft:resistance &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:resistance &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:resistance &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:resistance &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:fire_resistance"},
				{title: "effect &lt;player&gt; minecraft:fire_resistance &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:fire_resistance &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:fire_resistance &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:fire_resistance &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:water_breathing"},
				{title: "effect &lt;player&gt; minecraft:water_breathing &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:water_breathing &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:water_breathing &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:water_breathing &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:invisibility"},
				{title: "effect &lt;player&gt; minecraft:invisibility &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:invisibility &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:invisibility &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:invisibility &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:blindness"},
				{title: "effect &lt;player&gt; minecraft:blindness &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:blindness &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:blindness &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:blindness &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:night_vision"},
				{title: "effect &lt;player&gt; minecraft:night_vision &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:night_vision &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:night_vision &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:night_vision &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:hunger"},
				{title: "effect &lt;player&gt; minecraft:hunger &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:hunger &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:hunger &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:hunger &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:weakness"},
				{title: "effect &lt;player&gt; minecraft:weakness &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:weakness &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:weakness &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:weakness &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:poison"},
				{title: "effect &lt;player&gt; minecraft:poison &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:poison &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:poison &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:poison &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:wither"},
				{title: "effect &lt;player&gt; minecraft:wither &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:wither &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:wither &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:wither &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:health_boost"},
				{title: "effect &lt;player&gt; minecraft:health_boost &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:health_boost &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:health_boost &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:health_boost &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:absorption"},
				{title: "effect &lt;player&gt; minecraft:absorption &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:absorption &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:absorption &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:absorption &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:saturation"},
				{title: "effect &lt;player&gt; minecraft:saturation &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:saturation &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:saturation &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:saturation &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:glowing"},
				{title: "effect &lt;player&gt; minecraft:glowing &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:glowing &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:glowing &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:glowing &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:levitation"},
				{title: "effect &lt;player&gt; minecraft:levitation &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:levitation &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:levitation &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:levitation &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:luck"},
				{title: "effect &lt;player&gt; minecraft:luck &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:luck &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:luck &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:luck &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "effect &lt;player&gt; minecraft:unluck"},
				{title: "effect &lt;player&gt; minecraft:unluck &lt;seconds&gt;"},
				{title: "effect &lt;player&gt; minecraft:unluck &lt;seconds&gt; &lt;amplifier&gt;"},
				{title: "effect &lt;player&gt; minecraft:unluck &lt;seconds&gt; &lt;amplifier&gt; true"},
				{title: "effect &lt;player&gt; minecraft:unluck &lt;seconds&gt; &lt;amplifier&gt; false"},
				{title: "enchant &lt;player&gt; minecraft:protection"},
				{title: "enchant &lt;player&gt; minecraft:protection &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:fire_protection"},
				{title: "enchant &lt;player&gt; minecraft:fire_protection &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:feather_falling"},
				{title: "enchant &lt;player&gt; minecraft:feather_falling &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:blast_protection"},
				{title: "enchant &lt;player&gt; minecraft:blast_protection &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:projectile_protection"},
				{title: "enchant &lt;player&gt; minecraft:projectile_protection &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:respiration"},
				{title: "enchant &lt;player&gt; minecraft:respiration &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:aqua_affinity"},
				{title: "enchant &lt;player&gt; minecraft:aqua_affinity &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:thorns"},
				{title: "enchant &lt;player&gt; minecraft:thorns &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:depth_strider"},
				{title: "enchant &lt;player&gt; minecraft:depth_strider &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:frost_walker"},
				{title: "enchant &lt;player&gt; minecraft:frost_walker &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:binding_curse"},
				{title: "enchant &lt;player&gt; minecraft:binding_curse &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:sharpness"},
				{title: "enchant &lt;player&gt; minecraft:sharpness &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:smite"},
				{title: "enchant &lt;player&gt; minecraft:smite &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:bane_of_arthropods"},
				{title: "enchant &lt;player&gt; minecraft:bane_of_arthropods &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:knockback"},
				{title: "enchant &lt;player&gt; minecraft:knockback &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:fire_aspect"},
				{title: "enchant &lt;player&gt; minecraft:fire_aspect &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:looting"},
				{title: "enchant &lt;player&gt; minecraft:looting &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:sweeping"},
				{title: "enchant &lt;player&gt; minecraft:sweeping &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:efficiency"},
				{title: "enchant &lt;player&gt; minecraft:efficiency &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:silk_touch"},
				{title: "enchant &lt;player&gt; minecraft:silk_touch &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:unbreaking"},
				{title: "enchant &lt;player&gt; minecraft:unbreaking &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:fortune"},
				{title: "enchant &lt;player&gt; minecraft:fortune &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:power"},
				{title: "enchant &lt;player&gt; minecraft:power &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:punch"},
				{title: "enchant &lt;player&gt; minecraft:punch &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:flame"},
				{title: "enchant &lt;player&gt; minecraft:flame &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:infinity"},
				{title: "enchant &lt;player&gt; minecraft:infinity &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:luck_of_the_sea"},
				{title: "enchant &lt;player&gt; minecraft:luck_of_the_sea &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:lure"},
				{title: "enchant &lt;player&gt; minecraft:lure &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:mending"},
				{title: "enchant &lt;player&gt; minecraft:mending &lt;level&gt;"},
				{title: "enchant &lt;player&gt; minecraft:vanishing_curse"},
				{title: "enchant &lt;player&gt; minecraft:vanishing_curse &lt;level&gt;"},
				{title: "entitydata &lt;entity&gt; &lt;dataTag&gt;"},
				{title: "execute &lt;entity&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;command&gt;"},
				{title: "execute &lt;entity&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; detect &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; &lt;command&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; destroy"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; destroy"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; destroy &lt;dataTag&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; destroy &lt;dataTag&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; hollow"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; hollow"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; hollow &lt;dataTag&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; hollow &lt;dataTag&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; keep"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; keep"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; keep &lt;dataTag&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; keep &lt;dataTag&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; outline"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; outline"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; outline &lt;dataTag&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; outline &lt;dataTag&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; replace"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; replace"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; replace &lt;dataTag&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; replace &lt;dataTag&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;dataValue&gt; replace &lt;replaceTileName&gt; &lt;replaceDataValue&gt;"},
				{title: "fill &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;block&gt; &lt;state&gt; replace &lt;replaceTileName&gt; &lt;replaceDataValue&gt;"},
				{title: "gamemode survival"},
				{title: "gamemode survival &lt;player&gt;"},
				{title: "gamemode creative"},
				{title: "gamemode creative &lt;player&gt;"},
				{title: "gamemode adventure"},
				{title: "gamemode adventure &lt;player&gt;"},
				{title: "gamemode spectator"},
				{title: "gamemode spectator &lt;player&gt;"},
				{title: "gamerule &lt;rule name&gt; &lt;value&gt;"},
				{title: "gamerule commandBlockOutput true"},
				{title: "gamerule commandBlockOutput false"},
				{title: "gamerule disableElytraMovementCheck true"},
				{title: "gamerule disableElytraMovementCheck false"},
				{title: "gamerule doDaylightCycle true"},
				{title: "gamerule doDaylightCycle false"},
				{title: "gamerule doDaylightCycle true"},
				{title: "gamerule doDaylightCycle false"},
				{title: "gamerule doEntityDrops true"},
				{title: "gamerule doEntityDrops false"},
				{title: "gamerule doFireTick true"},
				{title: "gamerule doFireTick false"},
				{title: "gamerule doMobLoot true"},
				{title: "gamerule doMobLoot false"},
				{title: "gamerule doMobSpawning true"},
				{title: "gamerule doMobSpawning false"},
				{title: "gamerule doWeatherCycle true"},
				{title: "gamerule doWeatherCycle false"},
				{title: "gamerule keepInventory true"},
				{title: "gamerule keepInventory false"},
				{title: "gamerule logAdminCommands true"},
				{title: "gamerule logAdminCommands false"},
				{title: "gamerule maxEntityCramming 24"},
				{title: "gamerule maxEntityCramming &lt;value&gt;"},
				{title: "gamerule naturalRegeneration true"},
				{title: "gamerule naturalRegeneration false"},
				{title: "gamerule randomTickSpeed 3"},
				{title: "gamerule randomTickSpeed &lt;value&gt;"},
				{title: "gamerule reducedDebugInfo true"},
				{title: "gamerule reducedDebugInfo false"},
				{title: "gamerule sendCommandFeedback true"},
				{title: "gamerule sendCommandFeedback false"},
				{title: "gamerule showDeathMessages true"},
				{title: "gamerule showDeathMessages false"},
				{title: "gamerule spawnRadius 10"},
				{title: "gamerule spawnRadius &lt;value&gt;"},
				{title: "gamerule spectatorsGenerateChunks true"},
				{title: "gamerule spectatorsGenerateChunks false"},
				{title: "give &lt;player&gt; &lt;item&gt;"},
				{title: "give &lt;player&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "give &lt;player&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "give &lt;player&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "help"},
				{title: "help &lt;command&gt;"},
				{title: "help &lt;page&gt;"},
				{title: "kick &lt;player&gt;"},
				{title: "kick &lt;player&gt; &lt;reason&gt;"},
				{title: "kill"},
				{title: "kill &lt;player&gt;"},
				{title: "kill &lt;entity&gt;"},
				{title: "list"},
				{title: "list &lt;uuids&gt;"},
				{title: "locate EndCity"},
				{title: "locate Fortress"},
				{title: "locate Mansion"},
				{title: "locate Mineshaft"},
				{title: "locate Monument"},
				{title: "locate Stronghold"},
				{title: "locate Temple"},
				{title: "locate Village"},
				{title: "me &lt;action&gt;"},
				{title: "op &lt;player&gt;"},
				{title: "pardon &lt;player&gt;"},
				{title: "pardon-ip &lt;address&gt;"},
				{title: "particle &lt;name&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;xd&gt; &lt;yd&gt; &lt;zd&gt; &lt;speed&gt;"},
				{title: "particle &lt;name&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;xd&gt; &lt;yd&gt; &lt;zd&gt; &lt;speed&gt; &lt;count&gt;"},
				{title: "particle &lt;name&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;xd&gt; &lt;yd&gt; &lt;zd&gt; &lt;speed&gt; &lt;count&gt; &lt;mode&gt;"},
				{title: "particle &lt;name&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;xd&gt; &lt;yd&gt; &lt;zd&gt; &lt;speed&gt; &lt;count&gt; &lt;mode&gt; &lt;player&gt;"},
				{title: "particle &lt;name&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;xd&gt; &lt;yd&gt; &lt;zd&gt; &lt;speed&gt; &lt;count&gt; &lt;mode&gt; &lt;player&gt; &lt;params&gt;"},
				{title: "playsound &lt;sound&gt; master &lt;player&gt;"},
				{title: "playsound &lt;sound&gt; master &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "playsound &lt;sound&gt; master &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt;"},
				{title: "playsound &lt;sound&gt; master &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt;"},
				{title: "playsound &lt;sound&gt; master &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt; &lt;minimumVolume&gt;"},
				{title: "playsound &lt;sound&gt; music &lt;player&gt;"},
				{title: "playsound &lt;sound&gt; music &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "playsound &lt;sound&gt; music &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt;"},
				{title: "playsound &lt;sound&gt; music &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt;"},
				{title: "playsound &lt;sound&gt; music &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt; &lt;minimumVolume&gt;"},
				{title: "playsound &lt;sound&gt; record &lt;player&gt;"},
				{title: "playsound &lt;sound&gt; record &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "playsound &lt;sound&gt; record &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt;"},
				{title: "playsound &lt;sound&gt; record &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt;"},
				{title: "playsound &lt;sound&gt; record &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt; &lt;minimumVolume&gt;"},
				{title: "playsound &lt;sound&gt; weather &lt;player&gt;"},
				{title: "playsound &lt;sound&gt; weather &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "playsound &lt;sound&gt; weather &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt;"},
				{title: "playsound &lt;sound&gt; weather &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt;"},
				{title: "playsound &lt;sound&gt; weather &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt; &lt;minimumVolume&gt;"},
				{title: "playsound &lt;sound&gt; block &lt;player&gt;"},
				{title: "playsound &lt;sound&gt; block &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "playsound &lt;sound&gt; block &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt;"},
				{title: "playsound &lt;sound&gt; block &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt;"},
				{title: "playsound &lt;sound&gt; block &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt; &lt;minimumVolume&gt;"},
				{title: "playsound &lt;sound&gt; hostile &lt;player&gt;"},
				{title: "playsound &lt;sound&gt; hostile &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "playsound &lt;sound&gt; hostile &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt;"},
				{title: "playsound &lt;sound&gt; hostile &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt;"},
				{title: "playsound &lt;sound&gt; hostile &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt; &lt;minimumVolume&gt;"},
				{title: "playsound &lt;sound&gt; neutral &lt;player&gt;"},
				{title: "playsound &lt;sound&gt; neutral &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "playsound &lt;sound&gt; neutral &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt;"},
				{title: "playsound &lt;sound&gt; neutral &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt;"},
				{title: "playsound &lt;sound&gt; neutral &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt; &lt;minimumVolume&gt;"},
				{title: "playsound &lt;sound&gt; player &lt;player&gt;"},
				{title: "playsound &lt;sound&gt; player &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "playsound &lt;sound&gt; player &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt;"},
				{title: "playsound &lt;sound&gt; player &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt;"},
				{title: "playsound &lt;sound&gt; player &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt; &lt;minimumVolume&gt;"},
				{title: "playsound &lt;sound&gt; ambiant &lt;player&gt;"},
				{title: "playsound &lt;sound&gt; ambiant &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "playsound &lt;sound&gt; ambiant &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt;"},
				{title: "playsound &lt;sound&gt; ambiant &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt;"},
				{title: "playsound &lt;sound&gt; ambiant &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt; &lt;minimumVolume&gt;"},
				{title: "playsound &lt;sound&gt; voice &lt;player&gt;"},
				{title: "playsound &lt;sound&gt; voice &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "playsound &lt;sound&gt; voice &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt;"},
				{title: "playsound &lt;sound&gt; voice &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt;"},
				{title: "playsound &lt;sound&gt; voice &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;volume&gt; &lt;pitch&gt; &lt;minimumVolume&gt;"},
				{title: "publish"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.chest &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.chest &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.chest &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.chest &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.chest &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.chest &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.chest &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.chest &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.feet &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.feet &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.feet &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.feet &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.feet &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.feet &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.feet &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.feet &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.head &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.head &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.head &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.head &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.head &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.head &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.head &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.head &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.legs &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.legs &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.legs &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.armor.legs &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.legs &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.legs &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.legs &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.armor.legs &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.weapon.mainhand &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.weapon.mainhand &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.weapon.mainhand &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.weapon.mainhand &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.weapon.mainhand &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.weapon.mainhand &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.weapon.mainhand &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.weapon.mainhand &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.weapon.offhand &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.weapon.offhand &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.weapon.offhand &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.weapon.offhand &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.weapon.offhand &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.weapon.offhand &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.weapon.offhand &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.weapon.offhand &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.enderchest.&lt;slot_number&gt; &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.enderchest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.enderchest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.enderchest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.enderchest.&lt;slot_number&gt; &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.enderchest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.enderchest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.enderchest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.hotbar.&lt;slot_number&gt; &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.hotbar.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.hotbar.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.hotbar.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.hotbar.&lt;slot_number&gt; &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.hotbar.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.hotbar.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.hotbar.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.inventory.&lt;slot_number&gt; &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.inventory.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.inventory.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.inventory.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.inventory.&lt;slot_number&gt; &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.inventory.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.inventory.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.inventory.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.saddle &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.saddle &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.saddle &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.saddle &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.saddle &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.saddle &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.saddle &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.saddle &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.armor &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.armor &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.armor &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.armor &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.armor &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.armor &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.armor &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.armor &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.chest.&lt;slot_number&gt; &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.chest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.chest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.horse.chest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.chest.&lt;slot_number&gt; &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.chest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.chest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.horse.chest.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.villager.&lt;slot_number&gt; &lt;item&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.villager.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.villager.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem block &lt;x&gt; &lt;y&gt; &lt;z&gt; slot.villager.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.villager.&lt;slot_number&gt; &lt;item&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.villager.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.villager.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt;"},
				{title: "replaceitem entity &lt;selector&gt; slot.villager.&lt;slot_number&gt; &lt;item&gt; &lt;amount&gt; &lt;data&gt; &lt;dataTag&gt;"},
				{title: "save-all"},
				{title: "save-all &lt;flush&gt;"},
				{title: "save-off"},
				{title: "save-on"},
				{title: "say &lt;message&gt;"},
				{title: "scoreboard &lt;objectives&gt;"},
				{title: "scoreboard &lt;players&gt;"},
				{title: "scoreboard &lt;teams&gt;"},
				{title: "seed"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt;"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;dataValue&gt;"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;state&gt;"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;dataValue&gt; destroy"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;state&gt; destroy"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;dataValue&gt; destroy &lt;dataTag&gt;"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;state&gt; destroy &lt;dataTag&gt;"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;dataValue&gt; keep"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;state&gt; keep"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;dataValue&gt; keep &lt;dataTag&gt;"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;state&gt; keep &lt;dataTag&gt;"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;dataValue&gt; replace"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;state&gt; replace"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;dataValue&gt; replace &lt;dataTag&gt;"},
				{title: "setblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;state&gt; replace &lt;dataTag&gt;"},
				{title: "setidletimeout &lt;minutes&gt;"},
				{title: "setworldspawn"},
				{title: "setworldspawn &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "spawnpoint"},
				{title: "spawnpoint &lt;player&gt;"},
				{title: "spawnpoint &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "spreadplayers &lt;x&gt; &lt;z&gt; &lt;spreadDistance&gt; &lt;maxRange&gt; true &lt;players&gt;"},
				{title: "spreadplayers &lt;x&gt; &lt;z&gt; &lt;spreadDistance&gt; &lt;maxRange&gt; false &lt;players&gt;"},
				{title: "stats block &lt;x&gt; &lt;y&gt; &lt;z&gt; clear AffectedBlocks"},
				{title: "stats block &lt;x&gt; &lt;y&gt; &lt;z&gt; set AffectedBlocks &lt;selector&gt; &lt;objective&gt;"},
				{title: "stats entity &lt;selector&gt; clear AffectedBlocks"},
				{title: "stats entity &lt;selector&gt; set AffectedBlocks &lt;selector&gt; &lt;objective&gt;"},
				{title: "stats block &lt;x&gt; &lt;y&gt; &lt;z&gt; clear AffectedEntities"},
				{title: "stats block &lt;x&gt; &lt;y&gt; &lt;z&gt; set AffectedEntities &lt;selector&gt; &lt;objective&gt;"},
				{title: "stats entity &lt;selector&gt; clear AffectedEntities"},
				{title: "stats entity &lt;selector&gt; set AffectedEntities &lt;selector&gt; &lt;objective&gt;"},
				{title: "stats block &lt;x&gt; &lt;y&gt; &lt;z&gt; clear AffectedItems"},
				{title: "stats block &lt;x&gt; &lt;y&gt; &lt;z&gt; set AffectedItems &lt;selector&gt; &lt;objective&gt;"},
				{title: "stats entity &lt;selector&gt; clear AffectedItems"},
				{title: "stats entity &lt;selector&gt; set AffectedItems &lt;selector&gt; &lt;objective&gt;"},
				{title: "stats block &lt;x&gt; &lt;y&gt; &lt;z&gt; clear QueryResult"},
				{title: "stats block &lt;x&gt; &lt;y&gt; &lt;z&gt; set QueryResult &lt;selector&gt; &lt;objective&gt;"},
				{title: "stats entity &lt;selector&gt; clear QueryResult"},
				{title: "stats entity &lt;selector&gt; set QueryResult &lt;selector&gt; &lt;objective&gt;"},
				{title: "stats block &lt;x&gt; &lt;y&gt; &lt;z&gt; clear SuccessCount"},
				{title: "stats block &lt;x&gt; &lt;y&gt; &lt;z&gt; set SuccessCount &lt;selector&gt; &lt;objective&gt;"},
				{title: "stats entity &lt;selector&gt; clear SuccessCount"},
				{title: "stats entity &lt;selector&gt; set SuccessCount &lt;selector&gt; &lt;objective&gt;"},
				{title: "stop"},
				{title: "stopsound &lt;player&gt;"},
				{title: "stopsound &lt;player&gt; master"},
				{title: "stopsound &lt;player&gt; master &lt;sound&gt;"},
				{title: "stopsound &lt;player&gt; music"},
				{title: "stopsound &lt;player&gt; music &lt;sound&gt;"},
				{title: "stopsound &lt;player&gt; record"},
				{title: "stopsound &lt;player&gt; record &lt;sound&gt;"},
				{title: "stopsound &lt;player&gt; weather"},
				{title: "stopsound &lt;player&gt; weather &lt;sound&gt;"},
				{title: "stopsound &lt;player&gt; block"},
				{title: "stopsound &lt;player&gt; block &lt;sound&gt;"},
				{title: "stopsound &lt;player&gt; hostile"},
				{title: "stopsound &lt;player&gt; hostile &lt;sound&gt;"},
				{title: "stopsound &lt;player&gt; neutral"},
				{title: "stopsound &lt;player&gt; neutral &lt;sound&gt;"},
				{title: "stopsound &lt;player&gt; player"},
				{title: "stopsound &lt;player&gt; player &lt;sound&gt;"},
				{title: "stopsound &lt;player&gt; ambient"},
				{title: "stopsound &lt;player&gt; ambient &lt;sound&gt;"},
				{title: "stopsound &lt;player&gt; voice"},
				{title: "stopsound &lt;player&gt; voice &lt;sound&gt;"},
				{title: "summon &lt;entityName&gt;"},
				{title: "summon &lt;entityName&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "summon &lt;entityName&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;dataTag&gt;"},
				{title: "teleport &lt;target entity&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "teleport &lt;target entity&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;y-rot&gt; &lt;x-rot&gt;"},
				{title: "tell &lt;player&gt; &lt;message&gt;"},
				{title: "tellraw &lt;player&gt; &lt;jsonMessage&gt;"},
				{title: "testfor &lt;player&gt;"},
				{title: "testfor &lt;player&gt; &lt;dataTag&gt;"},
				{title: "testforblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;dataValue&gt;"},
				{title: "testforblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;state&gt;"},
				{title: "testforblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;dataValue&gt; &lt;dataTag&gt;"},
				{title: "testforblock &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;block&gt; &lt;state&gt; &lt;dataTag&gt;"},
				{title: "testforblocks &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; all"},
				{title: "testforblocks &lt;x1&gt; &lt;y1&gt; &lt;z1&gt; &lt;x2&gt; &lt;y2&gt; &lt;z2&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; masked"},
				{title: "time &lt;add&gt; &lt;value&gt;"},
				{title: "time &lt;query&gt; &lt;value&gt;"},
				{title: "time &lt;set&gt; &lt;value&gt;"},
				{title: "title &lt;player&gt; clear"},
				{title: "title &lt;player&gt; reset"},
				{title: "title &lt;player&gt; title &lt;jsonTitle&gt;"},
				{title: "title &lt;player&gt; subtitle &lt;jsonTitle&gt;"},
				{title: "title &lt;player&gt; actionbar &lt;jsonTitle&gt;"},
				{title: "title &lt;player&gt; times &lt;fadeIn&gt; &lt;stay&gt; &lt;fadeOut&gt;"},
				{title: "toggledownfall"},
				{title: "tp &lt;destinationPlayer&gt;"},
				{title: "tp &lt;player&gt; &lt;destinationPlayer&gt;"},
				{title: "tp &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt;"},
				{title: "tp &lt;player&gt; &lt;x&gt; &lt;y&gt; &lt;z&gt; &lt;yaw&gt; &lt;pitch&gt;"},
				{title: "trigger &lt;objective&gt; &lt;add&gt; &lt;value&gt;"},
				{title: "trigger &lt;objective&gt; &lt;set&gt; &lt;value&gt;"},
				{title: "weather &lt;clear&gt;"},
				{title: "weather &lt;clear&gt; &lt;duration&gt;"},
				{title: "weather &lt;rain&gt;"},
				{title: "weather &lt;rain&gt; &lt;duration&gt;"},
				{title: "weather &lt;thunder&gt;"},
				{title: "weather &lt;thunder&gt; &lt;duration&gt;"},
				{title: "whitelist add &lt;player&gt;"},
				{title: "whitelist list"},
				{title: "whitelist off"},
				{title: "whitelist on"},
				{title: "whitelist reload"},
				{title: "whitelist remove &lt;player&gt;"},
				{title: "worldborder add &lt;distance&gt;"},
				{title: "worldborder add &lt;distance&gt; &lt;time&gt;"},
				{title: "worldborder center &lt;x&gt; &lt;z&gt;"},
				{title: "worldborder damage amount &lt;damagePerBlock&gt;"},
				{title: "worldborder damage buffer &lt;distance&gt;"},
				{title: "worldborder get"},
				{title: "worldborder set &lt;distance&gt;"},
				{title: "worldborder set &lt;distance&gt; &lt;time&gt;"},
				{title: "worldborder warning distance &lt;distance&gt;"},
				{title: "worldborder warning time 15"},
				{title: "worldborder warning time &lt;time&gt;"},
				{title: "wsserver &lt;serverURI&gt;"},
				{title: "connect &lt;serverURI&gt;"},
				{title: "xp &lt;amount&gt;"},
				{title: "xp &lt;amount&gt; &lt;player&gt;"},
				{title: "xp &lt;amount&gt;L"},
				{title: "xp &lt;amount&gt;L &lt;player&gt;"}
			],
			fullTextSearch: false,
			searchFields: ['title'],
			fields: {
				title: 'title'
			},
			showNoResults: false
		});
	}
}
</script>
